### ISSUE TITLE
Create Base data

### ISSUE THREAD

**Issue by rasensio1** [rasensio1/the_pivot#19]

**Comment by MowAlon** [comment]
I'll start by modifying the existing seeds file to better meet our needs. This will also involve changing the db structure to some degree, so watch out for the migrations!

**Comment by MowAlon** [comment]
Need to remove zipcode, phone_number, street_name from users table

**Comment by MowAlon** [comment]
Pull request submitted. Expecting conflict with a migration we created, but that might be in another branch, so I'm not sure if/when we'll see that.
