### ISSUE TITLE
Business Admin - Add items to business

### ISSUE THREAD

**Issue by rasensio1** [rasensio1/the_pivot#20]

**Comment by rasensio1** [comment]
As a Business Admin with a registered Shop
    When I visit my profile page and click on "my shop"
I see a page where I can add/edit/delete photos
    And when I click on "add"
          I see a form with the fields (name, price, description, category, image)
     And when I fill in these fields and click "submit"
         I am redirected to the shop index page, and can view the new item

**Comment by MowAlon** [comment]
The CRUD basics are already in place for 'items', but we're transitioning to sell photos, and I've already setup the table for that. I'll change the controller and views over from items to photos. When done, I'll nuke the items table altogether.

**Comment by MowAlon** [comment]
Jason's actually been working on this one
